language: php

cache:
  directories:
    - .phpunit

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

matrix:
  include:
    - php: 5.4
      dist: trusty
      env: SYMFONY_PHPUNIT_REMOVE_RETURN_TYPEHINT=1
    - php: 5.5
      dist: trusty
      env: SYMFONY_PHPUNIT_REMOVE_RETURN_TYPEHINT=1
    - php: 5.6
      env: SYMFONY_PHPUNIT_REMOVE_RETURN_TYPEHINT=1
    - php: 7.0
      env: SYMFONY_PHPUNIT_REMOVE_RETURN_TYPEHINT=1

before_install:
  - phpenv config-rm xdebug.ini || true
  - |
    for PHP in $TRAVIS_PHP_VERSION $php_extra; do
      INI=~/.phpenv/versions/$PHP/etc/conf.d/travis.ini
      echo date.timezone = Europe/Paris >> $INI
      echo memory_limit = -1 >> $INI
      echo session.gc_probability = 0 >> $INI
    done
  - composer self-update

install:
  - if [[ $TRAVIS_PHP_VERSION != '5.5' ]]; then composer install ; fi
  - if [[ $TRAVIS_PHP_VERSION == '5.5' ]]; then composer update --prefer-lowest ; fi

script:
  - export SYMFONY_DEPRECATIONS_HELPER=max[self]=0
  - export SYMFONY_PHPUNIT_DIR=`pwd`/.phpunit
  - ./vendor/bin/simple-phpunit
